name: Commit and PR using gh CLI

on:
  push:
    branches:
      - main

jobs:
  commit-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Create new branch and commit changes
        env:
          GH_TOKEN: ${{ secrets.COMMIT_TOKEN }}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git checkout -b new-branch
          echo "Test commit" >> test.txt
          git add test.txt
          git commit -m "Add test commit"
          git push origin new-branch

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.COMMIT_TOKEN }}
        run: |
          gh pr create --base main --head new-branch --title "Automated PR: Add test commit" --body "This PR was created automatically by a GitHub Action."
