name: Commit and PR using gh CLI

on:
  pull_request:

jobs:
  commit-and-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: ${{ !contains(github.actor,'[bot]') }}
    env:
      NEW_PR_BRANCH: "${{ github.head_ref }}-auto"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      #https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow
      - name: 🧬 Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Create new branch and commit changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "snappi.mc-auto-snap@cool.com"
          git config --global user.name "Snappi Mc Auto Snap"
          git checkout -b "$NEW_PR_BRANCH"
          echo "Test commit" >> test.txt
          git add test.txt
          git commit -m "Add test commit"
          git push -f origin "$NEW_PR_BRANCH"

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base ${{ github.head_ref }} --head "$NEW_PR_BRANCH"  --title "Automated PR: Add test commit" --body "This PR was created automatically by a GitHub Action."

      - name: 🤖 Enable auto-merge
        run: gh pr merge --squash "$NEW_PR_BRANCH"
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
