name: Commit and PR using gh CLI

on:
  push:
    branches:
      - new-branch

jobs:
  commit-and-pr:
    runs-on: ubuntu-latest
    env:
      NEW_PR_BRANCH: "${{ github.ref }}-auto"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Create new branch and commit changes
        if: ${{ github.head_commit.message != 'Add test commit' }}
        env:
          GH_TOKEN: ${{ secrets.COMMIT_TOKEN }}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git checkout -b "$NEW_PR_BRANCH"
          echo "Test commit" >> test.txt
          git add test.txt
          git commit -m "Add test commit"
          git push origin "$NEW_PR_BRANCH"

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.COMMIT_TOKEN }}
        run: |
          gh pr create --base ${{ github.ref }} --head "$NEW_PR_BRANCH"  --title "Automated PR: Add test commit" --body "This PR was created automatically by a GitHub Action."

      - name: ✔ Approve a PR
        run: gh pr review --approve "$NEW_PR_BRANCH"
        env:
          GITHUB_TOKEN: ${{secrets.COMMIT_TOKEN}}

      - name: 🤖 Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GITHUB_TOKEN: ${{secrets.COMMIT_TOKEN}}
