name: Run on PR

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  run-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Run on PR
        run: echo "Run on PR or main"